# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe6cb015eafef8e66c207f21cd7f313f2cb6f01ec4fbeda68c584d96d7408970cf02a4ef5cd205740a842301a3365d83b8cc0c9708cef4204bac024fc3487283

test:
  secret_key_base: 25d6a3edd466fdcb68695d37f864895e4a21a15f8bcd0cd6a71fe4ffb6cec49e7be08f967a89bf63625ccb923100c264dbf7c56fcb63fe80efffabdb523937cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
